[package]
name = "k4_enrollment"
version = "0.1.0"
authors = ["Jimmy Tu"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"

[profile.release]
codegen-units = 1

opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
